include(cmakes/darwin/openssl.cmake)
include(cmakes/darwin/libzip.cmake)
include(cmakes/darwin/bzip2.cmake)
include(cmakes/darwin/xz.cmake)
include(cmakes/darwin/zstd.cmake)
include(cmakes/darwin/cpp-httplib.cmake)
include(cmakes/darwin/jwt-cpp.cmake)
include(cmakes/darwin/yaml-cpp.cmake)
